# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CxkpyVC5_O4AP2wu5ixEB5DW6XeVH3v5
"""

1)x = int(input("число:"))
y = x % 2
if y == 0:
    print("это число четное")
else:
    print("это число нечетное")

2)x = int(input("первое число:"))
y = int(input("второе число:"))
if y > x:
    print(y)
else:
    print(x)

3)x = int(input("первое координата:"))
y = int(input("второе координата:"))
z = (x + y)%2
if z > 0:
    print("NO")
else:
    print("YES")